name = "bt-to"
main = "./index.js"
type = "javascript"

kv_namespaces = [
  { binding = "data", id = "<kv namespace id>" }
]

account_id = "<cloudflare account id>"
workers_dev = true
route = { pattern = "https://api.hutt.io/bt-to/*", zone_name = "hutt.io" }
zone_id = "<cloudflare zone id>"
compatibility_date = "2024-05-21"

[triggers]
# Schedule cron triggers:
# - Every 15 minutes
crons = [ "*/15 * * * *" ]

[vars]
# Caching: API Responses
API_CACHE_TTL = 3600 # 1 Stunde in Sekunden
# Caching: Liste mit Werten in Datenbank
DATALIST_CACHE_TTL = 86400 # 24 Stunden in Sekunden
# Logging aktivieren
LOGGING_ENABLED = true
# Cache leeren
PURGE_CACHE = false
# Key Value Storage leeren
PURGE_KV = false
